---
# tasks file for ansible-role-redis

- name: Install | from yum
  # memo libjemalloc.so.3 from epel
  yum:
     name:  "{{ item }}"
     state: installed
     enablerepo: "remi, epel"
  with_items:
    - redis
  tags: ['redis']

- name: chmod log dir
  file:
    path:  "/var/log/redis"
    state: directory
    mode: "{{ var_log_redis_permission | default('0755') }}"
  tags: ['redis']

- name: chkconfig on
  service:
    name:    redis
    enabled: "{{ redis_service_on | default('yes') }}"
  tags: ['redis']

